/**
 * Regenerate `schemas/registry.json` from the `schemas/<type>/` tree.
 *
 * The registry is the single machine-readable index the website and tooling read; it is
 * never hand-edited. Run: `pnpm build:registry`.
 *
 * vct / @context URLs derive from configurable bases (env-overridable):
 *   GLIDE_CONTEXT_BASE (default https://schemas.glideidentity.app/contexts/)
 *   GLIDE_VCT_BASE     (default https://schemas.glideidentity.app/vct/)
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  contextFor,
  resolveBases,
  vctFor,
  REGISTRY_PATH,
  SCHEMAS_DIR,
  type Registry,
  type RegistryEntry,
  type VctMetadata,
} from '../packages/schema-tools/src/index.js';

/** Canonical credential types, in the order they appear in the FIDO "known use cases" set. */
const TYPE_ORDER = [
  'employee-id',
  'proof-of-employment',
  'bank-id',
  'phone-verification',
  'email-verification',
  'age-verification',
  'education-certificate',
  'boarding-pass',
] as const;

const SPECS = {
  w3cVcDataModel: 'W3C VC Data Model 2.0 (Recommendation, 15 May 2025)',
  sdJwtVc: 'draft-ietf-oauth-sd-jwt-vc-16 (24 Apr 2026)',
  sdJwt: 'RFC 9901 (Nov 2025)',
  jsonSchema: 'JSON Schema Draft 2020-12',
};

function relPath(id: string, ...parts: string[]): string {
  return join('schemas', id, ...parts);
}

function buildEntry(id: string, bases: ReturnType<typeof resolveBases>): RegistryEntry {
  const dir = join(SCHEMAS_DIR, id);
  const vctMetaPath = join(dir, 'sd-jwt-vc', 'vct-metadata.json');
  if (!existsSync(vctMetaPath)) {
    throw new Error(`Missing ${vctMetaPath}; cannot build registry entry for "${id}"`);
  }
  const vctMeta = JSON.parse(readFileSync(vctMetaPath, 'utf8')) as VctMetadata;

  return {
    id,
    name: vctMeta.name ?? id,
    description: vctMeta.description ?? '',
    version: '1.0.0',
    vct: vctFor(id, bases),
    context: contextFor(id, bases),
    specs: SPECS,
    paths: {
      schema: relPath(id, 'schema.json'),
      jsonldContext: relPath(id, 'jsonld', 'context.jsonld'),
      jsonldExample: relPath(id, 'jsonld', 'example.json'),
      sdJwtVcMetadata: relPath(id, 'sd-jwt-vc', 'vct-metadata.json'),
      sdJwtVcExample: relPath(id, 'sd-jwt-vc', 'example.json'),
      readme: relPath(id, 'README.md'),
    },
  };
}

function main(): void {
  const bases = resolveBases();
  const credentials = TYPE_ORDER.filter((id) => existsSync(join(SCHEMAS_DIR, id))).map((id) =>
    buildEntry(id, bases),
  );

  const registry: Registry = {
    $comment:
      'Generated by scripts/build-registry.ts — do not edit by hand. Run `pnpm build:registry`.',
    registryVersion: '1.0.0',
    // Deterministic so regeneration produces no spurious diff; bump when the schema set changes.
    generatedAt: '2026-06-05',
    bases,
    specs: SPECS,
    credentials,
  };

  writeFileSync(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`, 'utf8');
  console.log(`Wrote ${REGISTRY_PATH} with ${credentials.length} credential type(s).`);
}

main();
